path: /workdir/radish/nguyenqh/food_yolov8/Vietnamese_Food_data/data/OID  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/valid # val images (relative to 'path')

# Classes
names:
 [
      "hot-dog",
      "Apple",
      "Artichoke",
      "Asparagus",
      "Bagel",
      "Baked-goods",
      "Banana",
      "Beer",
      "Bell-pepper",
      "Bread",
      "Broccoli",
      "Burrito",
      "Cabbage",
      "Cake",
      "Candy",
      "Cantaloupe",
      "Carrot",
      "Common-fig",
      "Cookie",
      "Dessert",
      "French-fries",
      "Grape",
      "Guacamole",
      "Hot-dog",
      "Ice-cream",
      "Muffin",
      "Orange",
      "Pancake",
      "Pear",
      "Popcorn",
      "Pretzel",
      "Strawberry",
      "Tomato",
      "Waffle",
      "food-drinks",
      "Cheese",
      "Cocktail",
      "Coffee",
      "Cooking-spray",
      "Crab",
      "Croissant",
      "Cucumber",
      "Doughnut",
      "Egg",
      "Fruit",
      "Grapefruit",
      "Hamburger",
      "Honeycomb",
      "Juice",
      "Lemon",
      "Lobster",
      "Mango",
      "Milk",
      "Mushroom",
      "Oyster",
      "Pasta",
      "Pastry",
      "Peach",
      "Pineapple",
      "Pizza",
      "Pomegranate",
      "Potato",
      "Pumpkin",
      "Radish",
      "Salad",
      "food",
      "Sandwich",
      "Shrimp",
      "Squash",
      "Squid",
      "Submarine-sandwich",
      "Sushi",
      "Taco",
      "Tart",
      "Tea",
      "Vegetable",
      "Watermelon",
      "Wine",
      "Winter-melon",
      "Zucchini",
      "Banh_mi",
      "Banh_trang_tron",
      "Banh_xeo",
      "Bun_bo_Hue",
      "Bun_dau",
      "Com_tam",
      "Goi_cuon",
      "Pho",
      "Hu_tieu",
      "Xoi",
    ]
